### ISSUE TITLE
rustls support?

### ISSUE THREAD

**Issue by Masber** [rust-lang/git2-rs#998] opened 2023-11-01 21:34 UTC
Hi, I am using git2 crate and realised it depends on openssl-sys, Is there a plan to support rustls? I also checked the features and could not find anything related to rustls.

I would like to avoid this dependency because it breaks my binary portability due to:

> error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

thanks

**Comment by ehuss** [comment] 2023-11-01 21:51
Unfortunately there is no plan at this time. Closing as a duplicate of #623.

**Closed by ehuss** 2023-11-01 21:51 UTC
